import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FormMenu extends javax.swing.JFrame {
    Menu menu = new Menu();

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        NonAktif();
    }
    void Aktif(){
        bPesan.setEnabled(true);
        taPesanan.setEnabled(true);
        txtBayar.setEnabled(true);
        txtTagihan.setEnabled(true);
        txtKembali.setEnabled(true);
        cbEspresso.setEnabled(true);
        cbAmericano.setEnabled(true);
        cbLatte.setEnabled(true);
        cbCappuccino.setEnabled(true);
        cbFlat.setEnabled(true);
        cbMachiatto.setEnabled(true);
        cbChocolate.setEnabled(true);
        cbMatcha.setEnabled(true);
        cbRed.setEnabled(true);
        cbCaramel.setEnabled(true);
        txtJumlah1.setEnabled(true);
        txtJumlah2.setEnabled(true);
        txtJumlah3.setEnabled(true);
        txtJumlah4.setEnabled(true);
        txtJumlah5.setEnabled(true);
        txtJumlah6.setEnabled(true);
        txtJumlah7.setEnabled(true);
        txtJumlah8.setEnabled(true);
        txtJumlah9.setEnabled(true);
        txtJumlah10.setEnabled(true);
        bPesan.setEnabled(true);
    }
    void Bersih(){
        txtJumlah1.setText("");
        txtJumlah2.setText("");
        txtJumlah3.setText("");
        txtJumlah4.setText("");
        txtJumlah5.setText("");
        txtJumlah6.setText("");
        txtJumlah7.setText("");
        txtJumlah8.setText("");
        txtJumlah9.setText("");
        txtJumlah10.setText("");
        taPesanan.setText("");
        txtBayar.setText("");
        txtTagihan.setText("");
        txtKembali.setText("");
        cbEspresso.setSelected(false);
        cbAmericano.setSelected(false);
        cbLatte.setSelected(false);
        cbCappuccino.setSelected(false);
        cbFlat.setSelected(false);
        cbMachiatto.setSelected(false);
        cbChocolate.setSelected(false);
        cbMatcha.setSelected(false);
        cbRed.setSelected(false);
        cbCaramel.setSelected(false);
    }
    void NonAktif(){
        bPesan.setEnabled(false);
        taPesanan.setEnabled(false);
        txtTagihan.setEnabled(false);
        txtKembali.setEnabled(false);
        cbEspresso.setEnabled(false);
        cbAmericano.setEnabled(false);
        cbLatte.setEnabled(false);
        cbCappuccino.setEnabled(false);
        cbFlat.setEnabled(false);
        cbMachiatto.setEnabled(false);
        cbChocolate.setEnabled(false);
        cbMatcha.setEnabled(false);
        cbRed.setEnabled(false);
        cbCaramel.setEnabled(false);
        txtJumlah1.setEnabled(false);
        txtJumlah2.setEnabled(false);
        txtJumlah3.setEnabled(false);
        txtJumlah4.setEnabled(false);
        txtJumlah5.setEnabled(false);
        txtJumlah6.setEnabled(false);
        txtJumlah7.setEnabled(false);
        txtJumlah8.setEnabled(false);
        txtJumlah9.setEnabled(false);
        txtJumlah10.setEnabled(false);
        txtBayar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbAmericano = new javax.swing.JCheckBox();
        cbEspresso = new javax.swing.JCheckBox();
        cbCappuccino = new javax.swing.JCheckBox();
        cbLatte = new javax.swing.JCheckBox();
        cbMachiatto = new javax.swing.JCheckBox();
        cbFlat = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtJumlah1 = new javax.swing.JTextField();
        txtJumlah2 = new javax.swing.JTextField();
        txtJumlah4 = new javax.swing.JTextField();
        txtJumlah3 = new javax.swing.JTextField();
        txtJumlah6 = new javax.swing.JTextField();
        txtJumlah5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbChocolate = new javax.swing.JCheckBox();
        cbMatcha = new javax.swing.JCheckBox();
        cbRed = new javax.swing.JCheckBox();
        cbCaramel = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtJumlah8 = new javax.swing.JTextField();
        txtJumlah7 = new javax.swing.JTextField();
        txtJumlah9 = new javax.swing.JTextField();
        txtJumlah10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bPesan = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTagihan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPesanan = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        bKeluar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jPanel2.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(73, 73, 73));
        jLabel1.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 73, 73));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COFFEE");

        jLabel4.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Jumlah Beli");

        cbAmericano.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbAmericano.setForeground(new java.awt.Color(51, 51, 51));
        cbAmericano.setText("Americano");

        cbEspresso.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbEspresso.setForeground(new java.awt.Color(51, 51, 51));
        cbEspresso.setText("Expresso");

        cbCappuccino.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbCappuccino.setForeground(new java.awt.Color(51, 51, 51));
        cbCappuccino.setText("Cappuccino");

        cbLatte.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbLatte.setForeground(new java.awt.Color(51, 51, 51));
        cbLatte.setText("Latte");

        cbMachiatto.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbMachiatto.setForeground(new java.awt.Color(51, 51, 51));
        cbMachiatto.setText("Macchiato");

        cbFlat.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbFlat.setForeground(new java.awt.Color(51, 51, 51));
        cbFlat.setText("Flat White");

        jLabel21.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Rp. 25.000");

        jLabel10.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Rp. 20.000");

        jLabel22.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Rp. 23.000");

        jLabel23.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Rp. 25.000");

        jLabel24.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Rp. 25.000");

        jLabel25.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Rp. 25.000");

        txtJumlah1.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah1.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah1.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah2.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah2.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah2.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah4.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah4.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah4.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah3.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah3.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah3.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah6.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah6.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah6.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah5.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah5.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah5.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbFlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMachiatto, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbEspresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAmericano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLatte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCappuccino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAmericano)
                    .addComponent(jLabel21)
                    .addComponent(txtJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLatte)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCappuccino)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(txtJumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(cbFlat)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMachiatto)
                        .addComponent(jLabel25))
                    .addComponent(txtJumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));

        jLabel3.setBackground(new java.awt.Color(73, 73, 73));
        jLabel3.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(73, 73, 73));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NON COFFEE");

        jLabel7.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nama");

        jLabel8.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Jumlah Beli");

        cbChocolate.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbChocolate.setForeground(new java.awt.Color(51, 51, 51));
        cbChocolate.setText("Chocolate");
        cbChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChocolateActionPerformed(evt);
            }
        });

        cbMatcha.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbMatcha.setForeground(new java.awt.Color(51, 51, 51));
        cbMatcha.setText("Matcha");

        cbRed.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbRed.setForeground(new java.awt.Color(51, 51, 51));
        cbRed.setText("Red Velvet");

        cbCaramel.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        cbCaramel.setForeground(new java.awt.Color(51, 51, 51));
        cbCaramel.setText("Caramel");
        cbCaramel.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Rp. 20.000");

        jLabel12.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Rp. 23.000");

        jLabel13.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Rp. 25.000");

        jLabel14.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Rp. 25.000");

        txtJumlah8.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah8.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah8.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah7.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah7.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah7.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah9.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah9.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah9.setForeground(new java.awt.Color(51, 51, 51));

        txtJumlah10.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah10.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtJumlah10.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbChocolate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMatcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(11, 11, 11))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cbCaramel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtJumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMatcha)
                    .addComponent(jLabel12)
                    .addComponent(txtJumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRed)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtJumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCaramel)
                            .addComponent(jLabel14))))
                .addGap(29, 29, 29))
        );

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(73, 73, 73));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU COFFEE SHOP");

        bPesan.setBackground(new java.awt.Color(119, 198, 252));
        bPesan.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        bPesan.setForeground(new java.awt.Color(73, 73, 73));
        bPesan.setText("PESAN");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        jReset.setBackground(new java.awt.Color(51, 204, 0));
        jReset.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jReset.setForeground(new java.awt.Color(255, 255, 255));
        jReset.setText("RESET");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Jumlah Tagihan");

        txtTagihan.setBackground(new java.awt.Color(255, 255, 255));
        txtTagihan.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtTagihan.setForeground(new java.awt.Color(51, 51, 51));
        txtTagihan.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagihanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Uang Bayar");

        txtBayar.setBackground(new java.awt.Color(255, 255, 255));
        txtBayar.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtBayar.setForeground(new java.awt.Color(51, 51, 51));
        txtBayar.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBayarKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Uang Kembali");

        txtKembali.setBackground(new java.awt.Color(255, 255, 255));
        txtKembali.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        txtKembali.setForeground(new java.awt.Color(51, 51, 51));
        txtKembali.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        taPesanan.setBackground(new java.awt.Color(255, 255, 255));
        taPesanan.setColumns(20);
        taPesanan.setFont(new java.awt.Font("Barlow", 0, 21)); // NOI18N
        taPesanan.setForeground(new java.awt.Color(51, 51, 51));
        taPesanan.setRows(5);
        taPesanan.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(taPesanan);

        jLabel18.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(73, 73, 73));
        jLabel18.setText("Menu Yang Di Pesan :");

        bKeluar.setBackground(new java.awt.Color(255, 51, 0));
        bKeluar.setFont(new java.awt.Font("Barlow", 1, 21)); // NOI18N
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("(Jika sudah tekan Enter)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel17))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTagihan)
                                            .addComponent(txtBayar)
                                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jReset, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChocolateActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if (cbEspresso.isSelected()){
            menu.setJumlah(txtJumlah1.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=20000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbEspresso.getText()+"     Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbAmericano.isSelected()){
            menu.setJumlah(txtJumlah2.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbAmericano.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbLatte.isSelected()){
            menu.setJumlah(txtJumlah3.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=23000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbLatte.getText()+"    Rp.23000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbCappuccino.isSelected()){
            menu.setJumlah(txtJumlah4.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbCappuccino.getText()+"   Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbFlat.isSelected()){
            menu.setJumlah(txtJumlah5.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbFlat.getText()+"     Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbMachiatto.isSelected()){
            menu.setJumlah(txtJumlah6.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbMachiatto.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbChocolate.isSelected()){
            menu.setJumlah(txtJumlah7.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=20000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbChocolate.getText()+"    Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbMatcha.isSelected()){
            menu.setJumlah(txtJumlah8.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=23000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbChocolate.getText()+"    Rp.23000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbRed.isSelected()){
            menu.setJumlah(txtJumlah9.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbRed.getText()+"    Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        if (cbCaramel.isSelected()){
            menu.setJumlah(txtJumlah10.getText());
            int jumlah = menu.getJumlah();
            int total;
            int harga=25000;
            total=jumlah*harga;
            bayar=bayar+total;
            tampil +=cbCaramel.getText()+"   Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }
        taPesanan.setText(tampil+"==================================="+"\n"+"Total Belanja : "+bayar);
        txtTagihan.setText(Integer.toString(bayar));
    }//GEN-LAST:event_bPesanActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
       Bersih();
       Aktif();
    }//GEN-LAST:event_jResetActionPerformed

    private void txtTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagihanActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void txtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int UangBayar = Integer.parseInt(txtBayar.getText());
            int TotalBayar = Integer.parseInt(txtTagihan.getText());
            if (UangBayar<TotalBayar){
                JOptionPane.showMessageDialog(null, "Uang yang Dibayarkan Tidak Cukup!");
            }
            else {
                txtKembali.setText(Integer.toString(UangBayar - TotalBayar));
                String Nota=taPesanan.getText();
                taPesanan.setText(Nota+"\nUang Bayar : "+txtBayar.getText()+"\nUang Kembali : "+txtKembali.getText());
            }
        }
    }//GEN-LAST:event_txtBayarKeyPressed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        int x;
        x = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (x==JOptionPane.YES_NO_OPTION){
            dispose();
        }
        else{
            return;
        }
    }//GEN-LAST:event_bKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cbAmericano;
    private javax.swing.JCheckBox cbCappuccino;
    private javax.swing.JCheckBox cbCaramel;
    private javax.swing.JCheckBox cbChocolate;
    private javax.swing.JCheckBox cbEspresso;
    private javax.swing.JCheckBox cbFlat;
    private javax.swing.JCheckBox cbLatte;
    private javax.swing.JCheckBox cbMachiatto;
    private javax.swing.JCheckBox cbMatcha;
    private javax.swing.JCheckBox cbRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPesanan;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtJumlah1;
    private javax.swing.JTextField txtJumlah10;
    private javax.swing.JTextField txtJumlah2;
    private javax.swing.JTextField txtJumlah3;
    private javax.swing.JTextField txtJumlah4;
    private javax.swing.JTextField txtJumlah5;
    private javax.swing.JTextField txtJumlah6;
    private javax.swing.JTextField txtJumlah7;
    private javax.swing.JTextField txtJumlah8;
    private javax.swing.JTextField txtJumlah9;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtTagihan;
    // End of variables declaration//GEN-END:variables
}
